language: android

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # Target SDK version used to compile the project
    - android-23

    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    - sys-img-armeabi-v7a-android-21

cache:
  directories:
    - $HOME/.gradle/caches/2.10
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep build/outputs | tr "\n" ":")

before_script:
 - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &

script:
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace
  - rm /home/travis/.gradle/caches/2.10/plugin-resolution/cache.properties.lock

after_failure:
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

after_script:
  # print lint results details
  - for f in app/build/outputs/lint-results.html; do pandoc $f -t plain; done
  - for f in data/build/outputs/lint-results.html; do pandoc $f -t plain; done
