language: android
jdk:
    - oraclejdk7

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # Target SDK version used to compile the project
    - android-23

    # Additional components
    - extra-android-m2repository

script:
  - ./gradlew assembleDebug

notifications:
  slack:
    secure: dDqWAUl0Uf4JejLblaLqTZFb++9BLJvjhhdkgngD0M4TRk8trYgZkyuSNbGFwLA7rHlCDNYN9ggXLkZiirinykRns8x5GrOFfypun7QRlWjFrefiFlow1aA+Tq/8dpgfRSMs0mhTFc4TiszHXuEiCKp+Who0LlsOfFY3N6Jb2OlxjVyog1uMBI2GTWjMixpcaSWxOfGsjOvjN4U6vRHOeCgWK1JE2RglbVUQcuvmQEuxJBQTiBJmmIlX+kzEkeM9AVEaBb4TIIgqBbZtcQTtCtsnQJcbJVRvmL664UH93wMRECfbtH0Jeh26YpnuSQw3HPA2Nhlf7xli1p60TMjpJ/ozSpNUetyUu9OnJJUlO3TJo/9SpQjSL4eDztAkNtVAB2bx5RN1J/qNTl/6oNjTwUnTCohg7nJlzM7W5CvnxkQF/BVtWOnLyhltJNuqOoAYuqCHj3iBgXfip+cCQbzhDRfImGB5AYQK+fbqbCMvAuEGvB+ZSLQPFF99Kq42rOxzoLTa10RzGYHiWCGBh9KkHoZ/dD4OJX4QgPF23kHOq61ZZ3fGpMY2h9E9efStlQGZpP0BqUbZ+e5wn0hYXiLb4AtEyTobJ7OOjd6QhtAoM0ekOWoiIZn69endzpP2gKNaLWSf9ao14jEzpGkyif/sIqqAtxUfCfXSJ0C0PuthU1I=
