language: android
jdk:
    - oraclejdk7

android:
  components:
    # Use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # Target SDK version used to compile the project
    - android-23

    # Additional components
    - extra-android-m2repository

script:
  - ./gradlew assembleDebug